---
title: "p8105_hw6_cm4070"
author: "claire mobley"
date: "12/1/2021"
output: github_document 
---


```{r}
library(tidyverse)
set.seed(1)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Load and Clean the `Birthweight` Dataset

This code will change the baby sex numeric variable into a factor with 2 levels, "male" and "female"

```{r}
birthweight_data = read_csv("./birthweight.csv") %>% 
 mutate(babysex = factor(babysex, levels = c("1", "2"), labels = c("male", "female")),
        frace = factor(frace, levels = c("1", "2", "3", "4", "8", "9"), labels = c("white", "black", "asian", "puerto rican", "other", "unknown")), 
        malform = factor(malform, levels = c("0", "1"), labels = c("absent", "present")),
        mrace = factor(mrace, levels = c("1", "2", "3", "4", "8"), labels = c("white", "black", "asian", "puerto rican", "other"))) %>% 
drop_na() %>% 
select(babysex, bhead, blength, bwt, delwt, fincome, frace, gaweeks, malform, menarche, mheight, momage, mrace, parity, ppbmi, ppwt, smoken, wtgain)
```

Let's fit the model

```{r}
birthweight_data %>% 
  ggplot(aes(x = bwt, y = babysex)) +
  geom_point()
```

```{r}
fit = lm(bwt ~ babysex + bhead + blength + delwt + gaweeks + mheight + momage + mrace + ppbmi + ppwt + smoken + wtgain, data = birthweight_data)
```
 
Look at results..

```{r}
broom::glance(fit)

broom::tidy(fit) %>% 
select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "mrace", "mother race:")
  )
```

## Compare to other models

This model uses length at birth and gestational age as predictors: 

```{r}
fit1 = lm(bwt ~ blength + gaweeks, data = birthweight_data)
```

This model uses head circumference, length, sex, and all interactions between these as predictors

```{r}
fit2 = lm(bwt ~ bhead + blength + babysex + bhead * blength + bhead * babysex + blength * babysex + bhead * blength * babysex, data = birthweight_data)
```

